title: Visanet Uruguay
description: >
  Sitio mantenido por Visanet Uruguay con información publica para desarrolladores e integradores.

remote_theme: pmarsceill/just-the-docs
search_enabled: true

repository: visanet-uy/visanet-uy.github.io

permalink: pretty

# Aux links for the upper right navigation
aux_links:
    "Visanet corporativo":
      - "https://www.visanet.com.uy/"

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

exclude:
  - Gemfile
  - Gemfile.lock
